# Cloudflare Pages Configuration
name = "kyoussef-blog"
compatibility_date = "2024-08-21"

# Pages configuration
pages_build_output_dir = "dist"

# Environment configuration for Pages
[env.production]
route = "kyoussef.com/*"

[env.preview]
route = "preview.kyoussef.com/*"