# Cloudflare Pages Configuration
name = "kyoussef-blog"
compatibility_date = "2024-08-21"

[env.production]
route = "kyoussef.com/*"

[env.staging]
route = "staging.kyoussef.com/*"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.environment]
NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false"

# Headers configuration for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.ico"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects
[[redirects]]
from = "/cv"
to = "/about"
status = 301

[[redirects]]
from = "/resume"
to = "/about"
status = 301

[[redirects]]
from = "/contact"
to = "https://www.linkedin.com/in/kamalyoussef/"
status = 302
